/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Entitys.ChiTietDatPhong;
import Entitys.ChiTietSDDV;
import dao.imp.DatPhongDaoImp;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import common.Common;
import dao.imp.HoaDonDaoImp;
import dao.imp.SuDungDVDaoImp;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ChiTietForm extends javax.swing.JFrame {

    /**
     * Creates new form ChiTiet
     */
    DefaultTableModel defaultTableModel1;
    DefaultTableModel defaultTableModel2;
    private String maHD;
    private String tenKH;
    private String tenNV;
    private String trangThaiKH;
    public ChiTietForm(String maHD, String tenKH, String tenNV,String trangThaiKH) {
        initComponents();
        setLocationRelativeTo(null);

        this.maHD = maHD;
        this.tenKH = tenKH;
        this.tenNV = tenNV;
        this.trangThaiKH = trangThaiKH;

        txtMaHD.setText(maHD);
        txtTenKH.setText(tenKH);
        txtTenNV.setText(tenNV);
        txtTrangThai.setText(trangThaiKH);

        txtMaHD.setEditable(false);
        txtTenKH.setEditable(false);
        txtTenNV.setEditable(false);
        txtTrangThai.setEditable(false);

        defaultTableModel1 = new DefaultTableModel();
        defaultTableModel1.addColumn("Mã Phòng");
        defaultTableModel1.addColumn("Tên Phòng");
        defaultTableModel1.addColumn("Gía Tiền/Ngày");
        defaultTableModel1.addColumn("Ngày Đến");
        defaultTableModel1.addColumn("Ngày Đi");
        defaultTableModel1.addColumn("Tiền Phòng");
        tblDisplayDP.setModel(defaultTableModel1);

        //đưa dữ liệu vào bảng
        List<ChiTietDatPhong> chiTietDP = new DatPhongDaoImp().getChiTietDP(maHD);
        for (ChiTietDatPhong ctdp : chiTietDP) {
            Object[] objctdp = {ctdp.getMaP(), ctdp.getTenP(), Common.FormatNumber(ctdp.getGia()), Common.FomatDate(ctdp.getNgayDen()),
                Common.FomatDate(ctdp.getNgayDi()), Common.FormatNumber(ctdp.getTienP())};
            defaultTableModel1.addRow(objctdp);
        }

        defaultTableModel2 = new DefaultTableModel();
        defaultTableModel2.addColumn("Mã Dịch Vụ");
        defaultTableModel2.addColumn("Tên Dịch Vụ");
        defaultTableModel2.addColumn("Gía Tiền");
        defaultTableModel2.addColumn("Số lượng");
        defaultTableModel2.addColumn("Ngày Sử Dụng");
        defaultTableModel2.addColumn("Tiền DV");
        tblDisplaySDDV.setModel(defaultTableModel2);

        List<ChiTietSDDV> ctdv = new SuDungDVDaoImp().getCTDV(maHD);
        for (ChiTietSDDV ct : ctdv) {
            Object[] objctsddv = {ct.getMaDV(), ct.getTenDV(), Common.FormatNumber(ct.getGia()),
                ct.getSoLuong(), Common.FomatDate(ct.getNgaySD()), Common.FormatNumber(ct.getTienDV())};
            defaultTableModel2.addRow(objctsddv);
        }

        ChiTietDatPhong tienPhong = new DatPhongDaoImp().getTienPhong(maHD);
        txtTongTienPhong.setText(Common.FormatNumber(tienPhong.getTongTienPhong()));

        ChiTietSDDV tienDV = new SuDungDVDaoImp().getTongTienDV(maHD);
        txtTongTienDV.setText(Common.FormatNumber(tienDV.getTongTienDV()));

        float tien1 = Float.parseFloat(txtTongTienPhong.getText().replaceAll(",", ""));
        float tien2 = Float.parseFloat(txtTongTienDV.getText().replaceAll(",", ""));
        float tientong = tien1 + tien2;
        txtThanhToan.setText(Common.FormatNumber(tientong));
        
        //Ẩn button xóa khi trạng thái khách hàng đã rời đi
        if("Đang thuê".equals(txtTrangThai.getText())){
            btnXoaDatPhong.setEnabled(true);
            btnXoaSDDV.setEnabled(true);
        }else{
            btnXoaDatPhong.setEnabled(false);
            btnXoaSDDV.setEnabled(false);
        }
    }
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    private ChiTietForm() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplayDP = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtTongTienPhong = new javax.swing.JTextField();
        btnXoaDatPhong = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDisplaySDDV = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtTongTienDV = new javax.swing.JTextField();
        btnXoaSDDV = new javax.swing.JButton();
        txtThanhToan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnThanhToan_TraPhong = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xemchitiet.png"))); // NOI18N
        jLabel1.setText("Chi tiết hóa đơn");

        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Mã Hóa Đơn");

        txtMaHD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Mã - Tên Khách Hàng");

        txtTenKH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Mã -Tên Nhân Viên");

        txtTenNV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết sử dụng phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 0))); // NOI18N

        tblDisplayDP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDisplayDP);

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Tổng tiền phòng :");

        txtTongTienPhong.setEditable(false);
        txtTongTienPhong.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnXoaDatPhong.setBackground(new java.awt.Color(255, 51, 51));
        btnXoaDatPhong.setText("Xóa");
        btnXoaDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDatPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongTienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTongTienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaDatPhong))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết sử dụng dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 0))); // NOI18N

        tblDisplaySDDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDisplaySDDV);

        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Tổng tiền dịch vụ :");

        txtTongTienDV.setEditable(false);
        txtTongTienDV.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnXoaSDDV.setBackground(new java.awt.Color(255, 51, 51));
        btnXoaSDDV.setText("Xóa");
        btnXoaSDDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSDDVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongTienDV, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaSDDV, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTienDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnXoaSDDV))
                .addContainerGap())
        );

        txtThanhToan.setEditable(false);
        txtThanhToan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Thanh toán :  ");

        btnThanhToan_TraPhong.setBackground(new java.awt.Color(255, 255, 102));
        btnThanhToan_TraPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThanhToan_TraPhong.setForeground(new java.awt.Color(0, 153, 0));
        btnThanhToan_TraPhong.setText("Trả phòng + Thanh Toán ");
        btnThanhToan_TraPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToan_TraPhongActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Trạng Thái Khách Hàng");

        txtTrangThai.setEditable(false);
        txtTrangThai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(154, 154, 154)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addComponent(txtThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThanhToan_TraPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenNV)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThanhToan_TraPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThanhToan_TraPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToan_TraPhongActionPerformed
        // TODO add your handling code here:
        String[] maKH = tenKH.split(" ");
        boolean AnButtonThanhToan = new HoaDonDaoImp().AnButtonThanhToan(maKH[0]);
        if (AnButtonThanhToan) {
            JOptionPane.showMessageDialog(this, "Khách hàng này đã thanh toán rồi");
        } else {
            List<ChiTietDatPhong> chiTietDP = new DatPhongDaoImp().getChiTietDP(maHD);
            for (ChiTietDatPhong ctdp : chiTietDP) {
                Object[] objctdp = {ctdp.getMaP(), ctdp.getTenP(), Common.FormatNumber(ctdp.getGia()), Common.FomatDate(ctdp.getNgayDen()),
                    Common.FomatDate(ctdp.getNgayDi()), Common.FormatNumber(ctdp.getTienP())};

                boolean updateTrangThaiPhongSangTrong = new DatPhongDaoImp().updateTrangThaiPhongSangTrong(ctdp.getMaP());
                boolean updateTrangThaiKhachHang = new HoaDonDaoImp().updateTrangThaiKhachHang(maKH[0]);

                if (updateTrangThaiPhongSangTrong && updateTrangThaiKhachHang) {
                    JOptionPane.showMessageDialog(this, "Oke");
                    close();
                } else {
                    JOptionPane.showMessageDialog(this, "Thất bại");
                }
            }
        }
    }//GEN-LAST:event_btnThanhToan_TraPhongActionPerformed

    private void btnXoaDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDatPhongActionPerformed
        // TODO add your handling code here:
        
        int row = tblDisplayDP.getSelectedRow();
        boolean updateTrangThaiPhongSangTrong = new DatPhongDaoImp().updateTrangThaiPhongSangTrong(tblDisplayDP.getValueAt(row, 0)+"");
        boolean XoaDatPhong = new DatPhongDaoImp().XoaDatPhong(txtMaHD.getText(),tblDisplayDP.getValueAt(row, 0)+"");
        if(updateTrangThaiPhongSangTrong && XoaDatPhong){
            JOptionPane.showMessageDialog(this, "Đã xóa đặt phòng");
            close();
        }else{
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
            
    }//GEN-LAST:event_btnXoaDatPhongActionPerformed

    private void btnXoaSDDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSDDVActionPerformed
        // TODO add your handling code here:
        int row = tblDisplaySDDV.getSelectedRow();
        boolean XoaSuDungDV = new SuDungDVDaoImp().XoaSuDungDV(txtMaHD.getText(),tblDisplaySDDV.getValueAt(row, 0)+"");
        if(XoaSuDungDV){
            JOptionPane.showMessageDialog(this, "Đã xóa dịch vụ");
            close();
        }else{
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnXoaSDDVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThanhToan_TraPhong;
    private javax.swing.JButton btnXoaDatPhong;
    private javax.swing.JButton btnXoaSDDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDisplayDP;
    private javax.swing.JTable tblDisplaySDDV;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtThanhToan;
    private javax.swing.JTextField txtTongTienDV;
    private javax.swing.JTextField txtTongTienPhong;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
}
