/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Entitys.DichVu;
import dao.imp.DichVuDaoImp;
import java.text.NumberFormat;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class DichVuForm extends javax.swing.JFrame {

    /**
     * Creates new form DichVu
     */
    DefaultTableModel defaultTableModel;
    public DichVuForm() {
        initComponents();
        
        setLocationRelativeTo(null);

        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã DV");
        defaultTableModel.addColumn("Tên DV");
        defaultTableModel.addColumn("Gía Tiền");

        tblDisplayDV.setModel(defaultTableModel);
        
        defaultTableModel.setRowCount(0); //Xóa hết dữ liệu cũ của bảng
        List<DichVu> allDichVu = new DichVuDaoImp().getAllDichVu();
        for (DichVu dichVu : allDichVu) {
            Object[] objdv = {dichVu.getMaDV(),dichVu.getTenDV(),common.Common.FormatNumber(dichVu.getGia())};
            defaultTableModel.addRow(objdv);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFindbyID = new javax.swing.JButton();
        btnFindByName = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnLoadAll = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaDV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenDV = new javax.swing.JTextField();
        txtGiaTien = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplayDV = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1100, 750));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/service.png"))); // NOI18N
        jLabel5.setText("Dịch Vụ");

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        btnAdd.setForeground(new java.awt.Color(0, 153, 0));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);

        btnUpdate.setForeground(new java.awt.Color(0, 153, 0));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);

        btnDelete.setForeground(new java.awt.Color(0, 153, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);

        btnFindbyID.setForeground(new java.awt.Color(0, 153, 0));
        btnFindbyID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        btnFindbyID.setText("Tìm kiếm theo Mã");
        btnFindbyID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindbyIDActionPerformed(evt);
            }
        });
        jPanel1.add(btnFindbyID);

        btnFindByName.setForeground(new java.awt.Color(0, 153, 0));
        btnFindByName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        btnFindByName.setText("Tìm kiếm theo tên");
        btnFindByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindByNameActionPerformed(evt);
            }
        });
        jPanel1.add(btnFindByName);

        btnReset.setForeground(new java.awt.Color(0, 153, 0));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        btnReset.setText("Làm Mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset);

        btnLoadAll.setForeground(new java.awt.Color(0, 153, 0));
        btnLoadAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/load.png"))); // NOI18N
        btnLoadAll.setText("Xem Danh Sách");
        btnLoadAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoadAll);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 0))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Mã dịch vụ");

        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Tên dịch vụ");

        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Giá tiền");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaDV)
                    .addComponent(txtGiaTien, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(txtTenDV))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 0))); // NOI18N

        tblDisplayDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDisplayDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisplayDVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDisplayDV);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(387, 387, 387))))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadAllActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0); //Xóa hết dữ liệu cũ của bảng
        List<DichVu> allDichVu = new DichVuDaoImp().getAllDichVu();
        for (DichVu dichVu : allDichVu) {
            Object[] objdv = {dichVu.getMaDV(),dichVu.getTenDV(),common.Common.FormatNumber(dichVu.getGia())};
            defaultTableModel.addRow(objdv);
        }
    }//GEN-LAST:event_btnLoadAllActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String maDV = txtMaDV.getText().trim();
        String tenDV = txtTenDV.getText().trim();
        String giaTien = txtGiaTien.getText().trim();
        
        String err="";
        
        if(maDV.length()==0){
            err+="\nChưa nhập mã dịch vụ";
        }else{
            Pattern pat = Pattern.compile("^[DV]{2}+[0-9]{2,}$");
            if (!pat.matcher(maDV).find()) {
                err += "\nChưa đúng định dạng DV**";
            }
            boolean checkMaDV = new DichVuDaoImp().checkMaDV(maDV);
            if (checkMaDV) {
                err += "\nMã dich vụ đã tồn tại ";
            }
        }
        
        if(tenDV.length()==0){
            err+="\nChưa nhập tên dịch vụ";
        }else{
            boolean checkTenDV = new DichVuDaoImp().checkTenDV(tenDV);
            if(checkTenDV){
                err+="\nTên Dịch Vụ đã tồn tại";
            }
        }
        
        float GiaTien = 0;
        if (giaTien.length() == 0) {
            err += "\nChưa nhập giá tiền ";
        } else {
            try {
                giaTien = giaTien.replaceAll(",", "");
                GiaTien = Float.parseFloat(giaTien);
                if (GiaTien < 0) {
                    err += "\nGiá Tiền phải là số dương";
                }
            } catch (Exception e) {
                err += "\nGiá tiền phải là số";
            }
        }
        
        if(err.length()==0){
            DichVu dv = new DichVu();
            dv.setMaDV(maDV);
            dv.setTenDV(tenDV);
            dv.setGia(GiaTien);
            boolean insertDichVu = new DichVuDaoImp().insertDichVu(dv);
            if(insertDichVu){
                JOptionPane.showMessageDialog(this, "Thêm mới thành công");
                btnLoadAll.doClick();
                btnReset.doClick();
            }else{
                JOptionPane.showMessageDialog(this, "Thêm mới thất bại");
            }
        }else {
            JOptionPane.showMessageDialog(this, err);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFindbyIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindbyIDActionPerformed
        // TODO add your handling code here:
        txtMaDV.setEditable(false);
        String strMaDV = JOptionPane.showInputDialog("Nhập mã dịch vụ cần tìm:");
        if (strMaDV != null && strMaDV.length() > 0) {
            String maDV = String.valueOf(strMaDV);
            DichVu dichVu = new DichVuDaoImp().getDichVu(maDV);
            if (dichVu!= null) {
                txtMaDV.setText(dichVu.getMaDV() + "");
                txtTenDV.setText(dichVu.getTenDV() + "");
                txtGiaTien.setText(common.Common.FormatNumber(dichVu.getGia()) + "");
            } else {
                JOptionPane.showMessageDialog(this, "Không có dịch vụ mã: " + strMaDV);
            }
        }
    }//GEN-LAST:event_btnFindbyIDActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String maDV = txtMaDV.getText().trim();
        String tenDV = txtTenDV.getText().trim();
        String giaTien = txtGiaTien.getText().trim();
        txtMaDV.setEditable(false);
        String err="";
        
        if(maDV.length()==0){
            err+="\nChưa nhập mã dịch vụ";
        }else{
            Pattern pat = Pattern.compile("^[DV]{2}+[0-9]{2,}$");
            if (!pat.matcher(maDV).find()) {
                err += "\nChưa đúng định dạng DV**";
            }
        }
        
        if(tenDV.length()==0){
            err+="\nChưa nhập tên dịch vụ";
        }else{
            boolean checkTenDV = new DichVuDaoImp().checkTenDV(tenDV);
            if(checkTenDV){
                err+="\nTên Dịch Vụ đã tồn tại";
            }
        }
        
        float GiaTien = 0;
        if (giaTien.length() == 0) {
            err += "\nChưa nhập giá tiền ";
        } else {
            try {
                giaTien = giaTien.replaceAll(",", "");
                GiaTien = Float.parseFloat(giaTien);
                if (GiaTien < 0) {
                    err += "\nGiá Tiền phải là số dương";
                }
            } catch (Exception e) {
                err += "\nGiá tiền phải là số";
            }
        }
        
        if(err.length()==0){
            DichVu dv = new DichVu();
            dv.setMaDV(maDV);
            dv.setTenDV(tenDV);
            dv.setGia(GiaTien);
            boolean insertDichVu = new DichVuDaoImp().updateDichVu(dv);
            if(insertDichVu){
                JOptionPane.showMessageDialog(this, "Sửa mới thành công");
                btnLoadAll.doClick();
                btnReset.doClick();
            }else{
                JOptionPane.showMessageDialog(this, "Sửa mới thất bại");
            }
        }else {
            JOptionPane.showMessageDialog(this, err);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String maDV = txtMaDV.getText().trim();
        DichVu dv = new DichVu();
        dv.setMaDV(maDV);
        boolean deleteDichVu = new DichVuDaoImp().deleteDichVu(dv);
        if (deleteDichVu) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            btnLoadAll.doClick();
            btnReset.doClick();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtMaDV.setText("");
        txtTenDV.setText("");
        txtGiaTien.setText("");
        txtMaDV.setEditable(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnFindByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindByNameActionPerformed
        // TODO add your handling code here:
        String strTenDV = JOptionPane.showInputDialog("Nhập tên dịch vụ cần tìm:");

        List<DichVu> dichVuByName = new DichVuDaoImp().getDichVuByName(strTenDV);
        if (dichVuByName == null) {
            JOptionPane.showMessageDialog(this, "Không có nhân viên nào tên " + strTenDV);
        } else if (dichVuByName.isEmpty()) {
            
        } else {
            defaultTableModel.setRowCount(0);
            for (DichVu dichVu : dichVuByName) {
                Object[] objdv = {dichVu.getMaDV(),dichVu.getTenDV(),common.Common.FormatNumber(dichVu.getGia())};
                defaultTableModel.addRow(objdv);
            }
        }
    }//GEN-LAST:event_btnFindByNameActionPerformed

    private void tblDisplayDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisplayDVMouseClicked
        // TODO add your handling code here:
        txtMaDV.setEditable(false);
        int row = tblDisplayDV.getSelectedRow();
        txtMaDV.setText(tblDisplayDV.getValueAt(row, 0) + "");
        txtTenDV.setText(tblDisplayDV.getValueAt(row, 1) + "");
        txtGiaTien.setText(tblDisplayDV.getValueAt(row, 2) + "");
    }//GEN-LAST:event_tblDisplayDVMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DichVuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DichVuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DichVuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DichVuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DichVuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFindByName;
    private javax.swing.JButton btnFindbyID;
    private javax.swing.JButton btnLoadAll;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDisplayDV;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtMaDV;
    private javax.swing.JTextField txtTenDV;
    // End of variables declaration//GEN-END:variables
}
