/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Entitys.NhanVien;
import common.Common;
import dao.imp.NhanVienDaoImp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class NhanVienForm extends javax.swing.JFrame {

    /**
     * Creates new form NhanVienForm
     */
    DefaultTableModel defaultTableModel;
    public NhanVienForm() {
        initComponents();

        setLocationRelativeTo(null);

        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã NV");
        defaultTableModel.addColumn("Tên NV");
        defaultTableModel.addColumn("Giới Tính");
        defaultTableModel.addColumn("Ngày Sinh");
        defaultTableModel.addColumn("SDT");

        tblDisplayNV.setModel(defaultTableModel);
        
        List<NhanVien> allNhanVien = new NhanVienDaoImp().getAllNhanVien();
        for (NhanVien nhanVien : allNhanVien) {
            Object[] objnv = {nhanVien.getMaNV(), nhanVien.getTenNV(),
                Common.GioiTinh(nhanVien.isGioiTinh()), Common.FomatDate(nhanVien.getNgaySinh()), nhanVien.getSDT()};
            defaultTableModel.addRow(objnv);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdGioiTinh = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFindById = new javax.swing.JButton();
        btnFindByName = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnLoadAll = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        rdNam = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rdNu = new javax.swing.JRadioButton();
        txtTenNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplayNV = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/employee.png"))); // NOI18N
        jLabel1.setText("Nhân Viên");

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        btnAdd.setForeground(new java.awt.Color(0, 153, 0));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);

        btnUpdate.setForeground(new java.awt.Color(0, 153, 0));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);

        btnDelete.setForeground(new java.awt.Color(0, 153, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);

        btnFindById.setForeground(new java.awt.Color(0, 153, 0));
        btnFindById.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        btnFindById.setText("Tìm kiếm theo mã");
        btnFindById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindByIdActionPerformed(evt);
            }
        });
        jPanel1.add(btnFindById);

        btnFindByName.setForeground(new java.awt.Color(0, 153, 0));
        btnFindByName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/find.png"))); // NOI18N
        btnFindByName.setText("Tìm kiếm theo tên");
        btnFindByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindByNameActionPerformed(evt);
            }
        });
        jPanel1.add(btnFindByName);

        btnReset.setForeground(new java.awt.Color(0, 153, 0));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        btnReset.setText("Làm Mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset);

        btnLoadAll.setForeground(new java.awt.Color(0, 153, 0));
        btnLoadAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/load.png"))); // NOI18N
        btnLoadAll.setText("Xem Danh Sách");
        btnLoadAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoadAll);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Mã NV");

        rdGioiTinh.add(rdNam);
        rdNam.setText("Nam");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Tên NV");

        rdGioiTinh.add(rdNu);
        rdNu.setText("Nữ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Giới Tính");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Ngày Sinh");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("SĐT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rdNam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdNu)
                                .addGap(3, 3, 3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(209, 209, 209))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdNam)
                    .addComponent(rdNu))
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sach nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 0))); // NOI18N

        tblDisplayNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDisplayNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisplayNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDisplayNV);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(378, 378, 378))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadAllActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0); //Xóa hết dữ liệu cũ của bảng
        List<NhanVien> allNhanVien = new NhanVienDaoImp().getAllNhanVien();
        for (NhanVien nhanVien : allNhanVien) {
            Object[] objnv = {nhanVien.getMaNV(), nhanVien.getTenNV(),
                Common.GioiTinh(nhanVien.isGioiTinh()), Common.FomatDate(nhanVien.getNgaySinh()), nhanVien.getSDT()};
            defaultTableModel.addRow(objnv);
        }
    }//GEN-LAST:event_btnLoadAllActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String maNV = txtMaNV.getText().trim();
        String tenNV = txtTenNV.getText().trim();
        boolean gioiTinh = false;
        String ngaySinh = txtNgaySinh.getText().trim();
        String sDT = txtSDT.getText().trim();

        String err = "";

        if (maNV.length() == 0) {
            err += "\nChưa nhập mã nhân viên";
        } else {
            Pattern pat = Pattern.compile("^[NV]{2}+[0-9]{2,}$");
            if (!pat.matcher(maNV).find()) {
                err += "\nChưa đúng định dạng NV**";
            }
            boolean checkMaNV = new NhanVienDaoImp().checkMaNV(maNV);
            if (checkMaNV) {
                err += "\nMã nhân viên đã tồn tại ";
            }
        }

        if (tenNV.length() == 0) {
            err += "\nChưa nhập tên nhân viên";
        }

        if (!rdNam.isSelected() && !rdNu.isSelected()) {
            err += "\nChưa chọn giới tính";
        } else {
            if (rdNam.isSelected()) {
                gioiTinh = true;
            } else {
                gioiTinh = false;
            }
        }

        Date exNgaySinh = null;
        if (ngaySinh.length() == 0) {
            err += "\nChưa nhập ngày sinh";
        } else {
            SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yyyy");
            try {
                exNgaySinh = sf.parse(ngaySinh);
            } catch (ParseException ex) {
                err += "Kiểu ngày tháng năm chưa đúng định dạng dd/MM/yyyy";
            }
        }

        if (sDT.length() == 0) {
            err += "\nChưa nhập số điện thoại";
        } else {
            Pattern pat = Pattern.compile("^[0-9]{10,15}$");
            if (!pat.matcher(sDT).find()) {
                err += "\nSố điện thoại từ 10 đến 15 số";
            }
        }

        if (err.length() == 0) {
            NhanVien nv = new NhanVien();
            nv.setMaNV(maNV);
            nv.setTenNV(tenNV);
            nv.setGioiTinh(gioiTinh);
            nv.setNgaySinh(exNgaySinh);
            nv.setSDT(sDT);
            boolean insertNhanVien = new NhanVienDaoImp().insertNhanVien(nv);
            if (insertNhanVien) {
                JOptionPane.showMessageDialog(this, "Thêm mới thành công");
                btnLoadAll.doClick();
                btnReset.doClick();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm mới thất bại");
            }
        } else {
            JOptionPane.showMessageDialog(this, err);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFindByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindByIdActionPerformed
        // TODO add your handling code here:
        txtMaNV.setEditable(false);
        String strMaNV = JOptionPane.showInputDialog("Nhập mã nhân viên cần tìm:");
        if (strMaNV != null && strMaNV.length() > 0) {
            String maNV = String.valueOf(strMaNV);
            NhanVien maNV1 = new NhanVienDaoImp().getMaNV(maNV);
            if (maNV1 != null) {
                txtMaNV.setText(maNV1.getMaNV() + "");
                txtTenNV.setText(maNV1.getTenNV() + "");
                if (maNV1.isGioiTinh() == true) {
                    rdNam.setSelected(rootPaneCheckingEnabled);
                } else {
                    rdNu.setSelected(rootPaneCheckingEnabled);
                }
                txtNgaySinh.setText(common.Common.FomatDate(maNV1.getNgaySinh()) + "");
                txtSDT.setText(maNV1.getSDT() + "");
            } else {
                JOptionPane.showMessageDialog(this, "Không có nhân viên nào mã: " + strMaNV);
            }
        }
    }//GEN-LAST:event_btnFindByIdActionPerformed

    private void tblDisplayNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisplayNVMouseClicked
        // TODO add your handling code here:
        txtMaNV.setEditable(false);
        int row = tblDisplayNV.getSelectedRow();
        txtMaNV.setText(tblDisplayNV.getValueAt(row, 0) + "");
        txtTenNV.setText(tblDisplayNV.getValueAt(row, 1) + "");
        if (tblDisplayNV.getValueAt(row, 2) == "Nam") {
            rdNam.setSelected(rootPaneCheckingEnabled);
        } else {
            rdNu.setSelected(rootPaneCheckingEnabled);
        }
        txtNgaySinh.setText(tblDisplayNV.getValueAt(row, 3) + "");
        txtSDT.setText(tblDisplayNV.getValueAt(row, 4) + "");
    }//GEN-LAST:event_tblDisplayNVMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String maNV = txtMaNV.getText().trim();
        String tenNV = txtTenNV.getText().trim();
        boolean gioiTinh = false;
        String ngaySinh = txtNgaySinh.getText().trim();
        String sDT = txtSDT.getText().trim();
        txtMaNV.setEditable(false);
        String err = "";

        if (maNV.length() == 0) {
            err += "\nChưa nhập mã nhân viên";
        } else {
            Pattern pat = Pattern.compile("^[NV]{2}+[0-9]{2,}$");
            if (!pat.matcher(maNV).find()) {
                err += "\nChưa đúng định dạng NV**";
            }
        }

        if (tenNV.length() == 0) {
            err += "\nChưa nhập tên nhân viên";
        }

        if (!rdNam.isSelected() && !rdNu.isSelected()) {
            err += "\nChưa chọn giới tính";
        } else {
            if (rdNam.isSelected()) {
                gioiTinh = true;
            } else {
                gioiTinh = false;
            }
        }

        Date exNgaySinh = null;
        if (ngaySinh.length() == 0) {
            err += "\nChưa nhập ngày sinh";
        } else {
            SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yyyy");
            try {
                exNgaySinh = sf.parse(ngaySinh);
            } catch (ParseException ex) {
                err += "Kiểu ngày tháng năm chưa đúng định dạng dd/MM/yyyy";
            }
        }

        if (sDT.length() == 0) {
            err += "\nChưa nhập số điện thoại";
        } else {
            Pattern pat = Pattern.compile("^[0-9]{10,15}$");
            if (!pat.matcher(sDT).find()) {
                err += "\nSố điện thoại từ 10 đến 15 số";
            }
        }

        if (err.length() == 0) {
            NhanVien nv = new NhanVien();
            nv.setMaNV(maNV);
            nv.setTenNV(tenNV);
            nv.setGioiTinh(gioiTinh);
            nv.setNgaySinh(exNgaySinh);
            nv.setSDT(sDT);
            boolean updateNhanVien = new NhanVienDaoImp().updateNhanVien(nv);
            if (updateNhanVien) {
                JOptionPane.showMessageDialog(this, "Sửa mới thành công");
                btnLoadAll.doClick();
                btnReset.doClick();
            } else {
                JOptionPane.showMessageDialog(this, "Sửa mới thất bại");
            }
        } else {
            JOptionPane.showMessageDialog(this, err);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtMaNV.setEditable(true);
        txtMaNV.setText("");
        txtTenNV.setText("");
        rdGioiTinh.clearSelection();
        txtNgaySinh.setText("");
        txtSDT.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String maNV = txtMaNV.getText().trim();
        NhanVien nv = new NhanVien();
        nv.setMaNV(maNV);
        boolean deleteNhanVien = new NhanVienDaoImp().deleteNhanVien(nv);
        if (deleteNhanVien) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            btnLoadAll.doClick();
            btnReset.doClick();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFindByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindByNameActionPerformed
        // TODO add your handling code here:
        String strTenNV = JOptionPane.showInputDialog("Nhập tên nhân viên cần tìm:");

        List<NhanVien> nhanVienByName = new NhanVienDaoImp().getNhanVienByName(strTenNV);
        if (nhanVienByName == null || nhanVienByName.size()==0) {
            JOptionPane.showMessageDialog(this, "Không có nhân viên nào tên " + strTenNV);
        }else {
            defaultTableModel.setRowCount(0);
            for (NhanVien nhanVien : nhanVienByName) {
                Object[] objfnv = {nhanVien.getMaNV(), nhanVien.getTenNV(),
                    Common.GioiTinh(nhanVien.isGioiTinh()), Common.FomatDate(nhanVien.getNgaySinh()), nhanVien.getSDT()};
                defaultTableModel.addRow(objfnv);
            }
        }

    }//GEN-LAST:event_btnFindByNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFindById;
    private javax.swing.JButton btnFindByName;
    private javax.swing.JButton btnLoadAll;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup rdGioiTinh;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tblDisplayNV;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
